[versions]

#plugins
androidGradle = "7.2.2"
kotlin = "1.6.10"
hilt = "2.42"

#libraries
compose = "1.1.1"
composeConstraint = "1.0.1"
constraint = "2.1.4"
composeActivity = "1.3.1"
composeNavigation = "2.5.1"
coreKTX = "1.7.0"
lifecycleKTX = "2.3.1"
junit = "4.13.2"
androidxJUnit = "1.1.3"
espresso = "3.4.0"
navigationGraph = "1.1.0"
retrofit = "2.9.0"
hiltNavigation = "1.0.0"
room = "2.4.3"
moshi = "1.13.0"
composeAccompanist = "0.25.0"

[plugins]

androidApplication = {id = "com.android.application", version.ref = "androidGradle"}
androidLibrary = {id = "com.android.library", version.ref = "androidGradle"}
kotlin = {id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}

[libraries]

#production libraries
coreKTX = {module = "androidx.core:core-ktx", version.ref = "coreKTX"}
compose = {module = "androidx.compose.ui:ui", version.ref = "compose"}
composeMaterial = {module = "androidx.compose.material:material", version.ref = "compose"}
composePreview = {module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose"}
composeConstraint = {module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraint"}
constraint = {module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint"}
lifecycleKTX = {module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleKTX"}
composeActivity = {module = "androidx.activity:activity-compose", version.ref = "composeActivity"}
composeNavigation = {module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation"}
navigationGraph = {module = "net.lachlanmckee:hilt-compose-navigation-factory", version.ref = "navigationGraph"}
hilt = {module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hiltCompiler = {module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}
retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
gson = {module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
converterMoshi = {module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit"}
hiltNavigation = {module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation"}
room = {module = "androidx.room:room-runtime", version.ref = "room"}
moshi = {module = "com.squareup.moshi:moshi", version.ref = "moshi"}
roomKtx = {module = "androidx.room:room-ktx", version.ref = "room"}
composeAccompanistSwipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "composeAccompanist" }

# test libraries
testJunit = {module = "junit:junit", version.ref = "junit"}

# test android libraries
testAndroidJunit = {module = "androidx.test.ext:junit", version.ref = "androidxJUnit"}
testAndroidEspresso = {module = "androidx.test.espresso:espresso-core", version.ref = "espresso"}
testAndroidCompose = {module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose"}

# debug libraries
debugComposeManifest = {module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose"}
debugComposeTooling = {module = "androidx.compose.ui:ui-tooling", version.ref = "compose"}

# annotation processor libraries
navigationGraphAP = {module = "net.lachlanmckee:hilt-compose-navigation-factory-compiler", version.ref = "navigationGraph"}
roomAP = {module = "androidx.room:room-compiler", version.ref = "room"}
moshiAP = {module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi"}

# classpaths
hiltClasspath = {module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt"}